### ISSUE TITLE
Ploomber Convert feedback

### ISSUE THREAD

**Issue by onyekaugochukwu** [ploomber/contributing#2]
1. The next stop would be to able to select more than one pdf file.
2. We should also be able to merge the pdf files.
3. There should also be a means to compress the size of the combined pdfs just in case it becomes huge.
4. Also, we could have automatically generated page numbers. 
5. And we should have a page-break detector so that pages do not break in-between code.

**Comment by edublancas** [comment]
excellent, thanks for your feedback!
