### ISSUE TITLE
Doc: Change the yellow color in the ploomber-core

### ISSUE THREAD

**Issue by tonykploomber** [ploomber/contributing#21]
The yellow color isn't apparent when the page background is white, we need to change that color to others

<img width="1131" alt="Screenshot 2023-02-06 at 11 53 34 AM" src="https://user-images.githubusercontent.com/123580782/217034320-bb483876-2352-419e-9c2e-f6f425821936.png">

**Comment by edublancas** [comment]
closing in favor of https://github.com/ploomber/contributing/issues/26
