### ISSUE TITLE
ensure doc building fails when a notebook fails

### ISSUE THREAD

**Issue by edublancas** [ploomber/contributing#23]
we must ensure that all the projects built on jupyter-book fail on readthedocs whenever a notebook fails (by default, [this isn't the case](https://readthedocs.org/projects/jupysql/builds/19424552/) - this build succeeded but a notebook failed).

We already enabled this on sklearn-evaluation by setting the [fail_on_warning](https://github.com/ploomber/sklearn-evaluation/blob/89b107fdeba0489c2a74e6dead7b50b0a8b40e6c/readthedocs.yaml#L21). However, we haven't set this in other projects since there are still other warnings that we haven't fixed and will cause the docs to fail. So we should change the settings, see what happens to the readthedocs build and check if we fix the warnings (or add the [ignored warnings](https://github.com/ploomber/sklearn-evaluation/blob/9c0c894bad790e335e4f33b88de1316d63dae454/docs/conf.py#L131) list, note that some projects have _conf.yml instead of conf.py, so ignoring warnings will be different)

- [ ] jupysql
- [ ] ploomber-engine
- [ ] ploomber-core

**Comment by yafimvo** [comment]
@edublancas `ploomber-engine` is working fine without any changes

**Comment by edublancas** [comment]
cool,  I see we already have the flag, so all good: https://github.com/ploomber/ploomber-engine/blob/209d012c0f529f61189dd9edb35eed6e53041cf9/.readthedocs.yml#L17

we can close this then
