### ISSUE TITLE
disabling version check in readthedocs

### ISSUE THREAD

**Issue by edublancas** [ploomber/contributing#26]
Periodically, we show a message to users alerting them of updates, see https://github.com/ploomber/contributing/issues/21 for a screenshot.

This sometimes pollutes our readthedocs builds, so we should get rid of them, to fix it, we can set the `PLOOMBER_VERSION_CHECK_DISABLED` in the readthedocs environment.

- [ ] jupysql
- [ ] ploomer-engine
- [ ] sklearn-evaluation

**Comment by edublancas** [comment]
we need to modify the readthedocs config on each project: https://github.com/ploomber/ploomber/blob/master/readthedocs.yaml

**Comment by TegveerG** [comment]
@edublancas This task is not showing up on Asana

**Comment by edublancas** [comment]
we started syncing stuff in a asana a few months ago, so old issues won't sync - thanks for creating the task in asana

**Comment by TegveerG** [comment]
Hi @edublancas, the [PR](https://github.com/ploomber/ploomber-engine/pull/79) for ploomber-engine works fine when using the method you mentioned (including variable under`pre_build`). However, doing the same for sklearn-evaluation and JupySQL does not successfully run the test. I also looked up readthedocs documentation and implemented other ways like using `pre_build_commands` and initializing a `requirements.txt` file for these packages but they don't work either. Any ideas on how to fix this?

**Comment by edublancas** [comment]
reviewed your PR, it still need changes before we can say it's working. let's get that merged and then we work on the others

**Comment by TegveerG** [comment]
@edublancas  Should I mark this task as complete in Asana, even though the issue in sklearn package remains to be fixed?

**Comment by edublancas** [comment]
I closed it by accident, we should close it until all repos have been fixed. re-opening now

let's keep the asana one open as well
