### ISSUE TITLE
index community contributions

### ISSUE THREAD

**Issue by edublancas** [ploomber/contributing#34]
@Palashio suggested compiling community contributions; I like that idea.

we can create a document here (perhaps call it `contributions.md` is there any better name? ) to list everything that the community produces: blog posts, tutorials, etc. we can also link to their socials so we recognize them.

it can also help us to keep those materials up to date: whenever we make API breaking changes, we can let the authors know so they can update their materials

**Comment by edublancas** [comment]
https://towardsdatascience.com/running-sql-queries-in-jupyter-notebook-using-jupysql-duckdb-and-mysql-3c53fbe40f8d

**Comment by edublancas** [comment]
https://duckdb.org/docs/guides/python/jupyter
https://docs.hydra.so/analyze/jupyter
https://clickhouse.com/docs/en/integrations/sql-clients/jupysql/

**Comment by idomic** [comment]
Maybe `community-articles`

**Comment by edublancas** [comment]
or `community-content.md`? since it's more general
