### ISSUE TITLE
verify black formatting

### ISSUE THREAD

**Issue by edublancas** [ploomber/contributing#44]
we lint with flake8 and format with black. the problem is that if the contributor's local setup doesn't match what we have in the CI (or they're using another formatter, often inadvertently, as their IDE might be configured to format .py files) their PRs often will edit files completely unrelated to the GitHub issue. Hence, we end up with many files that only have format changes (and the CI passes because flake8 might consider them valid) making the PR more difficult and potentially causing merge conflicts.

as an alternative, we can add an extra step to our CI: we can run black and detect if any files were changed, if so, we can fail the CI so the contributor runs it locally and pushes again.

thoughts? do you think this will help prevent the issue or is it too much?

@idomic @tonykploomber @yafimvo @neelasha23

**Comment by tonykploomber** [comment]
I think the goal here is we want to make sure the developer runs a standard configuration on black & flake8

How about we add one more CMD command in invoke as: `>invoke ploomber-format` so it will run the black & flake8 internally with our pre-defined black & flake8 configuration file. By doing that, the formatting & linting setting can be refined as the ploomber-fashion

**Comment by edublancas** [comment]
I think we have to pick our poison:

1. Currently, we have something similar to what @tonykploomber is suggesting: `pkgmt format` - however, new contributors often skip that step, so we end up with polluted PRs
2. What @idomic suggests implies adding a commit to the contributor's PR, which will automatically trigger a new set of github actions (I'm not sure if the old ones are canceled)
3. What I proposed in my top comment will lead to CIs failing (but they'll fail pretty fast, after a few seconds of being triggered)

**Comment by edublancas** [comment]
What @tonykploomber mention is right: adding a commit on top of each commit will degrade the user experience

> For 3, this is already happening on flake8 right? (we saw some issues with it in the past). So what's missing is adding black to that step essentially.

It's not happening currently. flake8 only checks the format but does not apply any formatting or new commits


Something I've seen in other projects is to tell bots to perform certain actions. e.g., someone can post "hey apply black to this PR", then it'll add a new commit.

**Comment by tonykploomber** [comment]
We are discussing two things:

1. If your goal is just to notify **sooner** user there might be some formatting issues, I don't mind adding extra CI just to check linting part

2. Another thing we are discussing is how to make all contributor to run `pkgmt format`, I think it's reasonable to expect all contributor to run `pkgmt format` if they want to make a qualified PR in our project.

So if the linting CI fails we probably can just show some message that `Please run "pkgmt format" to format and check your code styling to pass the CI`

**Comment by tonykploomber** [comment]
> Something I've seen in other projects is to tell bots to perform certain actions. e.g., someone can post "hey apply black to this PR", then it'll add a new commit.

This can be a good to have feature, but only on-demand

**Comment by yafimvo** [comment]
As we discussed internally, I think we can standardize our lint configuration using [black configuration](https://black.readthedocs.io/en/stable/usage_and_configuration/the_basics.html#configuration-format) using `[tool.black]`. We can define some acceptable rules and add them to [pyproject.toml](https://github.com/ploomber/jupysql/blob/master/pyproject.toml).

**Comment by edublancas** [comment]
> As we discussed internally, I think we can standardize our lint configuration using [black configuration](https://black.readthedocs.io/en/stable/usage_and_configuration/the_basics.html#configuration-format) using [tool.black]. We can define some acceptable rules and add them to [pyproject.toml](https://github.com/ploomber/jupysql/blob/master/pyproject.toml).

Is no configuration causing problems currently? I'd assume that since we don't have configuration in our pyproject.toml,  we're using black's defaults

**Comment by yafimvo** [comment]
Oh, good point. maybe it depends on the IDE?

**Comment by edublancas** [comment]
hey @jorisroovers, random question:

In your PR (https://github.com/ploomber/jupysql/pull/325), you mentioned that you skipped running `pkgmt format` because it formats too many files. I checked out main, ran `pkgmt format` and it didn't change anything:

```
Running: black .
All done! ✨ 🍰 ✨
43 files left unchanged.
Running: nbqa black .
All done! ✨ 🍰 ✨
1 file left unchanged.
black passed!
```

Any ideas why? Could it be that you have black settings configured in your IDE? Can you run a quick test and let us know what happens if you run `pkgmt format` in JupySQL's master branch?

**Comment by jorisroovers** [comment]
On very latest master (https://github.com/ploomber/jupysql/commit/f35305f8116c232f4070409c2ecf8367236d8124), I get this:

```sh
❯ pkgmt format
Running: black .
reformatted /Users/jroovers/repos/jupysql/src/tests/test_inspect.py
reformatted /Users/jroovers/repos/jupysql/src/sql/connection.py

All done! ✨ 🍰 ✨
2 files reformatted, 59 files left unchanged.
Running: nbqa black .
All done! ✨ 🍰 ✨
34 files left unchanged.
black passed!
```

So I think that's just an issue with a recent commit, seems to work fine otherwise.

I just reran `pkgmt format` on https://github.com/ploomber/jupysql/pull/325 and it worked now (I just pushed a commit with fixes). I think it might have been a PEBKAC before (did run from CLI, not IDE), but I've closed the terminal so can't go back and check.

**Comment by edublancas** [comment]
team: I've implemented a GitHub workflow that will allow running `pkgmt format` on a PR by commenting `/format`. Will open a PR and tag you all.

**Comment by jorisroovers** [comment]
> I think it might have been a PEBKAC before (did run from CLI, not IDE), but I've closed the terminal so can't go back and check.

Just realized what actually happened. I forked of master when starting on my PR, when https://github.com/ploomber/jupysql/commit/f40f651ed263c0ad57704f9690817ddb1f5f4521 was the latest commit:

```sh
❯ git checkout f40f651ed263c0ad57704f9690817ddb1f5f4521
❯ black --check .
would reformat /private/tmp/jupysql/src/sql/ggplot/__init__.py
would reformat /private/tmp/jupysql/src/sql/ggplot/geom/__init__.py
would reformat /private/tmp/jupysql/src/sql/ggplot/aes.py
would reformat /private/tmp/jupysql/src/sql/ggplot/geom/geom_boxplot.py
would reformat /private/tmp/jupysql/src/sql/ggplot/geom/geom_histogram.py
would reformat /private/tmp/jupysql/src/sql/ggplot/facet_wrap.py
would reformat /private/tmp/jupysql/src/sql/ggplot/ggplot.py
would reformat /private/tmp/jupysql/src/tests/test_ggplot.py
would reformat /private/tmp/jupysql/src/sql/plot.py

Oh no! 💥 💔 💥
9 files would be reformatted, 49 files would be left unchanged.
```

Had resynced to master later which is why this wasn't recurring.

I'd suggest also adding `black --check .` to your CI to avoid merging any unformatted code since at the time of writing there's still formatting errors on master (https://github.com/ploomber/jupysql/commit/e65b4094765d8ae043ece0696ff97a17d76e8533):

```sh
❯ black --check .
would reformat /private/tmp/jupysql/src/tests/test_inspect.py
would reformat /private/tmp/jupysql/src/sql/connection.py

Oh no! 💥 💔 💥
2 files would be reformatted, 58 files would be left unchanged.
```

**Comment by edublancas** [comment]
I didn't know `black` had a `--check` option. I'll add it!
