### ISSUE TITLE
adding license metadata to our packages

### ISSUE THREAD

**Issue by edublancas** [ploomber/contributing#47]
see: https://github.com/ploomber/core/issues/54 for context.

I noticed some of our packages are still missing license metadata

https://github.com/ploomber/sklearn-evaluation/blob/master/setup.py
https://github.com/ploomber/ploomber-engine/blob/main/setup.py

(there might be more, we need to check jupysql)

**Comment by edublancas** [comment]
example of how to fix it: https://github.com/ploomber/core/blob/f81a4ce8f4d8b9e3dbc1b5a4a630ddc072ad884c/setup.py#L43

**Comment by tl3119** [comment]
Here is the PR for ploomber-engine: https://github.com/ploomber/ploomber-engine/pull/80
Sklearn-evaluation is blocked by the last PR
Jupysql already has the license metadata
