### ISSUE TITLE
pinned pydata-sphinx-theme

### ISSUE THREAD

**Issue by edublancas** [ploomber/contributing#50]
we had to pin pydata-sphinx-theme due to this: https://github.com/pydata/pydata-sphinx-theme/issues/1274 in this repository and will possibly need to do it in other repos, so once a fix is in place, we should ensure we remove the pinned version

**Comment by edublancas** [comment]
the issue has been closed so we can now remove the pinned version.

also we can remove it from here: https://github.com/search?q=repo%3Aploomber%2Fjupysql%20pydata-sphinx-theme&type=code

**Comment by edublancas** [comment]
@tl3119 - any progress on this one?

**Comment by tl3119** [comment]
For this one, is that we just remove the pinned version, that is remove `pydata-sphinx-theme<0.13.2` on environment.yml file and also in environment.lock.yml?

**Comment by edublancas** [comment]
only from environment.yml , then open a PR and we'll see if the tests pass

**Comment by edublancas** [comment]
also we need to check if we pinned it in other repos: ploomber-engine, pkgmt, sklearn-evaluation, ploomber-core

**Comment by tl3119** [comment]
Sure, I will do that now

**Comment by edublancas** [comment]
can you share a list of where is it pinned and where is it not?

looks like at least jupysql https://github.com/ploomber/jupysql/blob/b0c30bf1020a73c0a30d9362c598d99d7ac5a0fe/doc/environment.yml#L30 and sklearn-evaluation are pinned

**Comment by tl3119** [comment]
Sure!
Yeah, jupysql and sklaern-evaluation are pinned. 
jupysql-interactive-connection is also pinned: https://github.com/ploomber/jupysql-interactive-connection/blob/main/doc/environment.yml#LL30C7-L30C13 
Ploomber-engine is not pinned: https://github.com/ploomber/ploomber-engine/blob/main/doc/environment.yml
pkgmt is not pinned: https://github.com/ploomber/pkgmt/blob/main/doc/environment.yml
ploomber-core is not pinned: https://github.com/ploomber/core/blob/main/doc/environment.yml

**Comment by tl3119** [comment]
I have submitted the PR for this issue: https://github.com/ploomber/jupysql/pull/573

**Comment by edublancas** [comment]
we still have a few pending ones right? I just closed jupysql but I think there are others that are pending.

**Comment by tl3119** [comment]
Yeah, jupysql-interactive-connection is also pinned, I will open a PR for that.

**Comment by edublancas** [comment]
you can ignore jupysql-interactive-connection, we moved the code to jupysql-plugin

so looks like we can close this right? since the only ones that have pinned are jupysql, sklearn-eval and jupysql-interactive-connection

jupysql has been fixed
sklearn-eval has an open PR
jupysql-interactive-connection will  be ignored

**Comment by tl3119** [comment]
> you can ignore jupysql-interactive-connection, we moved the code to jupysql-plugin
> 
> so looks like we can close this right? since the only ones that have pinned are jupysql, sklearn-eval and jupysql-interactive-connection
> 
> jupysql has been fixed sklearn-eval has an open PR jupysql-interactive-connection will be ignored

Yes!
