### ISSUE TITLE
collaboration with trino

### ISSUE THREAD

**Issue by edublancas** [ploomber/contributing#61]
We now have a trino integration: https://jupysql.ploomber.io/en/latest/integrations/trinodb.html

Let's contact their team and see if they want to collaborate. Adding an example to their docs would be great, a blog post also works.

I already opened an issue: https://github.com/trinodb/trino/issues/15785

but opening this one so we don't lose track.

@lfunderburk: please keep an eye on the issue I opened, and follow up if needed

**Comment by lfunderburk** [comment]
On it - thank you Eduardo

**Comment by edublancas** [comment]
we got a [response](https://github.com/trinodb/trino/issues/15785#issuecomment-1567457907)  - let's give them a few days and see it it's resolved.
