### ISSUE TITLE
add grayskull to conda recipes

### ISSUE THREAD

**Issue by edublancas** [ploomber/contributing#63]
we need to add grayskull to the remaining conda-forge recipes (we tested it with jupysql)

change we need to apply: https://github.com/conda-forge/jupysql-feedstock/commit/4e75ac044dbfc33e1310ba19158d5dff6a215f44

repos: https://ploomber-contributing.readthedocs.io/en/latest/maintainer/conda-forge.html

**Comment by edublancas** [comment]
test

**Comment by tl3119** [comment]
I have submitted a pull request to conda-forge. https://github.com/conda-forge/staged-recipes/pull/22972
I am little confused for the last step: adding version updates. `conda-forge.yml` is not in the `staged-recipes` repository, how should I change this file?

**Comment by tl3119** [comment]
Got it. I have submitted to ploomber-engine. Please check.

**Comment by tl3119** [comment]
Is there anything I need to do for this task?

**Comment by edublancas** [comment]
there are a few other repositories that need change. listed here: https://ploomber-contributing.readthedocs.io/en/latest/maintainer/conda-forge.html

**Comment by edublancas** [comment]
great work @tl3119!
