### ISSUE TITLE
apply black formatting to our projects

### ISSUE THREAD

**Issue by edublancas** [ploomber/contributing#8]
We should format our projects using [black](https://github.com/psf/black) since it's become the standard in Python. I've been mainly using yapf, and we haven't enforced any formatted.

The challenge is that applying it to a whole project might conflict with existing PRs. So I suggest we apply it once all significant PRs are closed.

We should apply to at least the following projects:

- [x] sklearn-evaluation
- [x] ploomber-engine
- [x] jupysql
- [x] ploomber-core

thoughts? @idomic

**Comment by edublancas** [comment]
Note that this also requires customizing some flake8 rules since they conflict with black, [here's an example](https://github.com/psf/black/issues/315)

I'll update this sample setup.cfg with the appropriate config:

```cfg
[flake8]
# this one might change depending on the project
exclude = doc/_build/
max-line-length = 88
extend-ignore = E203
```

**Comment by idomic** [comment]
Check this one <https://sbarnea.com/lint/black/> out.

**Comment by edublancas** [comment]
all four projects listed in the first commend are now formatted with black
