### ISSUE TITLE
Issue on page /contributing/process-outline.html

### ISSUE THREAD

**Issue by nooodle-soup** [ploomber/contributing#84]
Unclear where Acceptance Criteria is to be defined.
Suggest clarifying that the Acceptance Criteria goes in the Issue created.

**Comment by edublancas** [comment]
can you open a PR?

**Comment by nooodle-soup** [comment]
Working on it

**Comment by nooodle-soup** [comment]
Opened a PR. Unable to add reviewers

**Comment by nooodle-soup** [comment]
Fixed in #85

**Comment by edublancas** [comment]
@nooodle-soup  FYI: in your PR you can write `Closes #X`, and github will close the issue when the PR is merged.

**Comment by nooodle-soup** [comment]
Got it! Thanks!
